import { Injectable, Logger } from '@nestjs/common';
import PDFDocument from 'pdfkit';
import type { ExportManifest, ExportType, WhiteLabelSnapshot } from '@signalkit/shared';
import type { PackDocumentRow, EvidenceData, PackRow } from './export-renderer.service';
import { ROLE_BRIEF_DOCUMENTS } from '@signalkit/exports';
import type { RoleBriefType } from '@signalkit/shared';

// Flat 2D palette — no gradients
const COLORS = {
  black: '#111111',
  gray: '#555555',
  lightGray: '#aaaaaa',
  border: '#cccccc',
  accent: '#1a1a1a',
  bg: '#ffffff',
  sectionLine: '#dddddd',
} as const;

/**
 * PDF export engine using pdfkit. Flat 2D style — no gradients, no
 * glassmorphism. Produces readable PDFs for Full Pack, Founder Summary,
 * Investor Memo, Roadmap, and Agency Client exports.
 *
 * RTL note: pdfkit has limited bidi support. Arabic/Hebrew content is rendered
 * in LTR order with a manifest flag `rtlContentWarning`. Full RTL layout
 * requires a follow-up RTL PDF engine or a headless browser renderer.
 */
@Injectable()
export class ExportPdfService {
  private readonly logger = new Logger(ExportPdfService.name);

  async render(
    type: ExportType,
    pack: PackRow,
    documents: PackDocumentRow[],
    ev: EvidenceData,
    manifest: ExportManifest,
    whiteLabelSettings: WhiteLabelSnapshot | null,
  ): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const chunks: Buffer[] = [];
      const doc = new PDFDocument({
        margin: 60,
        size: 'A4',
        info: {
          Title: pack.title,
          Author: whiteLabelSettings?.preparedBy ?? 'SignalKit',
          Subject: type,
          Keywords: `product pack, ${pack.depth}, ${pack.primaryLanguage}`,
          Creator: whiteLabelSettings?.hideSignalKitBrand ? (whiteLabelSettings.brandName ?? 'SignalKit') : 'SignalKit',
        },
      });

      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      try {
        this.renderTitlePage(doc, pack, type, whiteLabelSettings);
        this.renderTableOfContents(doc, documents, type, ev);
        this.renderDocuments(doc, pack, documents, type, ev);
        this.renderEvidenceAppendix(doc, ev);
        this.renderFooter(doc, manifest, whiteLabelSettings);
      } catch (err) {
        doc.end();
        reject(err);
        return;
      }

      doc.end();
    });
  }

  // ── Section renderers ─────────────────────────────────────────────────────

  private renderTitlePage(doc: PDFKit.PDFDocument, pack: PackRow, type: ExportType, wl: WhiteLabelSnapshot | null): void {
    const brandName = wl?.brandName ?? 'SignalKit';
    const clientName = wl?.clientName;

    // Title block
    doc.moveDown(4);
    doc
      .font('Helvetica-Bold')
      .fontSize(28)
      .fillColor(COLORS.black)
      .text(pack.title, { align: 'center' });

    doc.moveDown(0.5);
    doc
      .font('Helvetica')
      .fontSize(13)
      .fillColor(COLORS.gray)
      .text(this.exportTypeLabel(type), { align: 'center' });

    doc.moveDown(0.5);
    doc
      .fontSize(11)
      .fillColor(COLORS.lightGray)
      .text(`${pack.depth.replace(/_/g, ' ')} depth · ${pack.verticalTemplate.replace(/_/g, ' ')} vertical · ${pack.primaryLanguage.toUpperCase()}`, { align: 'center' });

    // Separator
    doc.moveDown(2);
    doc.moveTo(60, doc.y).lineTo(doc.page.width - 60, doc.y).strokeColor(COLORS.sectionLine).lineWidth(1).stroke();
    doc.moveDown(2);

    // Meta info
    const meta = [
      clientName ? `Prepared for: ${clientName}` : null,
      `Prepared by: ${wl?.preparedBy ?? brandName}`,
      `Generated: ${new Date().toISOString().slice(0, 10)}`,
      `Pack version: ${pack.version}`,
    ].filter(Boolean) as string[];

    doc.font('Helvetica').fontSize(10).fillColor(COLORS.gray);
    for (const line of meta) {
      doc.text(line, { align: 'center' });
    }

    // Disclaimer
    doc.moveDown(4);
    const disclaimer = wl?.customDisclaimer ??
      'This document was generated from real market signals and evidence. Assumptions are marked as such. ' +
      'Unresolved questions must not be treated as answered. Do not rely on this document as legal or financial advice.';

    doc.fontSize(9).fillColor(COLORS.lightGray).text(disclaimer, { align: 'center' });

    if (!wl?.hideSignalKitBrand) {
      doc.moveDown(1);
      doc.fontSize(8).fillColor(COLORS.lightGray).text('Generated by SignalKit / NicheOS', { align: 'center' });
    }

    doc.addPage();
  }

  private renderTableOfContents(doc: PDFKit.PDFDocument, documents: PackDocumentRow[], type: ExportType, _ev: EvidenceData): void {
    doc.font('Helvetica-Bold').fontSize(16).fillColor(COLORS.black).text('Table of Contents');
    doc.moveDown(0.5);
    doc.moveTo(60, doc.y).lineTo(doc.page.width - 60, doc.y).strokeColor(COLORS.sectionLine).lineWidth(0.5).stroke();
    doc.moveDown(0.5);

    const includedDocs = this.docsForType(type, documents);
    let n = 1;
    for (const d of includedDocs) {
      doc.font('Helvetica').fontSize(10).fillColor(COLORS.black).text(`${n++}. ${d.title}`);
    }

    // Always include appendices
    doc.font('Helvetica').fontSize(10).fillColor(COLORS.gray).text(`${n++}. Evidence & Assumptions Appendix`);
    doc.text(`${n}. Source Appendix`);

    doc.addPage();
  }

  private renderDocuments(doc: PDFKit.PDFDocument, _pack: PackRow, documents: PackDocumentRow[], type: ExportType, _ev: EvidenceData): void {
    const includedDocs = this.docsForType(type, documents);
    for (const d of includedDocs) {
      this.renderDocumentSection(doc, d);
    }
  }

  private renderDocumentSection(doc: PDFKit.PDFDocument, d: PackDocumentRow): void {
    doc.font('Helvetica-Bold').fontSize(14).fillColor(COLORS.black).text(d.title);
    doc.moveDown(0.25);
    doc.moveTo(60, doc.y).lineTo(doc.page.width - 60, doc.y).strokeColor(COLORS.accent).lineWidth(1).stroke();
    doc.moveDown(0.5);

    // Render markdown-ish content with basic formatting
    const lines = d.body.split('\n');
    for (const line of lines) {
      if (line.startsWith('# ')) {
        doc.font('Helvetica-Bold').fontSize(14).fillColor(COLORS.black).text(line.replace(/^#+ /, ''));
      } else if (line.startsWith('## ')) {
        doc.font('Helvetica-Bold').fontSize(12).fillColor(COLORS.black).text(line.replace(/^#+ /, ''));
      } else if (line.startsWith('### ')) {
        doc.font('Helvetica-Bold').fontSize(10).fillColor(COLORS.gray).text(line.replace(/^#+ /, ''));
      } else if (line.startsWith('- ') || line.startsWith('* ')) {
        doc.font('Helvetica').fontSize(9).fillColor(COLORS.black).text(`  • ${line.slice(2)}`);
      } else if (line.startsWith('> ')) {
        doc.font('Helvetica-Oblique').fontSize(9).fillColor(COLORS.gray).text(`  ${line.slice(2)}`);
      } else if (line.trim() === '---' || line.trim() === '***') {
        doc.moveDown(0.25);
        doc.moveTo(60, doc.y).lineTo(doc.page.width - 60, doc.y).strokeColor(COLORS.sectionLine).lineWidth(0.5).stroke();
        doc.moveDown(0.25);
      } else if (line.trim() === '') {
        doc.moveDown(0.3);
      } else {
        const clean = line.replace(/\*\*(.*?)\*\*/g, '$1').replace(/_(.*?)_/g, '$1');
        doc.font('Helvetica').fontSize(9).fillColor(COLORS.black).text(clean, { lineGap: 1 });
      }
    }

    doc.addPage();
  }

  private renderEvidenceAppendix(doc: PDFKit.PDFDocument, ev: EvidenceData): void {
    doc.font('Helvetica-Bold').fontSize(14).fillColor(COLORS.black).text('Evidence & Assumptions Appendix');
    doc.moveDown(0.5);

    // Quality gate summary
    if (ev.qualityGate) {
      doc.font('Helvetica-Bold').fontSize(11).text('Quality Gate Summary');
      doc.font('Helvetica').fontSize(9).fillColor(COLORS.gray);
      doc.text(`Status: ${ev.qualityGate.status} | Passed: ${ev.qualityGate.passedCount} | Warnings: ${ev.qualityGate.warnCount} | Failed: ${ev.qualityGate.failCount}`);
      doc.moveDown(0.5);
    }

    // Claims
    doc.font('Helvetica-Bold').fontSize(11).fillColor(COLORS.black).text(`Claims (${ev.claims.length})`);
    doc.font('Helvetica').fontSize(9).fillColor(COLORS.black);
    for (const c of ev.claims) {
      doc.text(`• [${c.type} · ${c.confidenceLevel}] ${c.text}`);
    }
    doc.moveDown(0.5);

    // Assumptions
    doc.font('Helvetica-Bold').fontSize(11).fillColor(COLORS.black).text(`Assumptions (${ev.assumptions.length})`);
    doc.font('Helvetica-Oblique').fontSize(9).fillColor(COLORS.gray).text('Assumptions are not validated facts. They must be tested before implementation.');
    doc.font('Helvetica').fontSize(9).fillColor(COLORS.black);
    for (const a of ev.assumptions) {
      doc.text(`• [${a.validationStatus}] ${a.text}`);
    }
    doc.moveDown(0.5);

    // Constraints
    if (ev.constraints.length > 0) {
      doc.font('Helvetica-Bold').fontSize(11).fillColor(COLORS.black).text(`Constraints (${ev.constraints.length})`);
      doc.font('Helvetica').fontSize(9);
      for (const c of ev.constraints) {
        doc.text(`• [${c.category}] ${c.text}`);
      }
      doc.moveDown(0.5);
    }

    // Unresolved questions
    if (ev.unresolvedQuestions.length > 0) {
      doc.font('Helvetica-Bold').fontSize(11).fillColor(COLORS.black).text(`Unresolved Questions (${ev.unresolvedQuestions.length})`);
      doc.font('Helvetica-Oblique').fontSize(9).fillColor(COLORS.gray).text('These questions must not be answered by assumption during implementation.');
      doc.font('Helvetica').fontSize(9).fillColor(COLORS.black);
      for (const q of ev.unresolvedQuestions) {
        doc.text(`• [${q.priority}] ${q.text}`);
      }
      doc.moveDown(0.5);
    }

    // Source appendix
    doc.addPage();
    doc.font('Helvetica-Bold').fontSize(14).fillColor(COLORS.black).text('Source Appendix');
    doc.moveDown(0.5);
    if (ev.sourceRefs.length === 0) {
      doc.font('Helvetica').fontSize(9).fillColor(COLORS.gray).text('No sources collected for this project.');
    } else {
      for (const s of ev.sourceRefs) {
        doc.font('Helvetica-Bold').fontSize(9).fillColor(COLORS.black).text(s.title ?? 'Untitled Source');
        doc.font('Helvetica').fontSize(8).fillColor(COLORS.gray);
        doc.text(`Adapter: ${s.adapter}`);
        if (s.url) doc.text(`URL: ${s.url}`);
        doc.moveDown(0.3);
      }
    }
  }

  private renderFooter(doc: PDFKit.PDFDocument, manifest: ExportManifest, wl: WhiteLabelSnapshot | null): void {
    const footer = wl?.footerText ?? (wl?.hideSignalKitBrand ? '' : 'Generated by SignalKit — signalkit.io');
    if (!footer) return;

    const range = doc.bufferedPageRange();
    for (let i = 0; i < range.count; i++) {
      doc.switchToPage(range.start + i);
      doc
        .font('Helvetica')
        .fontSize(7)
        .fillColor(COLORS.lightGray)
        .text(
          `${footer} | ${manifest.generatedAt.slice(0, 10)} | Page ${i + 1} of ${range.count}`,
          60,
          doc.page.height - 30,
          { align: 'center', width: doc.page.width - 120 },
        );
    }
  }

  // ── Helpers ───────────────────────────────────────────────────────────────

  private docsForType(type: ExportType, documents: PackDocumentRow[]): PackDocumentRow[] {
    const docMap = new Map(documents.map((d) => [d.docType, d]));

    // Role-mapped PDF types use role brief document selection
    const roleMap: Partial<Record<ExportType, RoleBriefType>> = {
      founder_summary_pdf: 'founder',
      investor_memo_pdf: 'investor',
    };
    const role = roleMap[type];
    if (role) {
      return (ROLE_BRIEF_DOCUMENTS[role] as string[])
        .map((dt: string) => docMap.get(dt))
        .filter((d): d is PackDocumentRow => d !== undefined);
    }

    if (type === 'roadmap_pdf') {
      return [docMap.get('roadmap'), docMap.get('mvp_scope'), docMap.get('feature_checklist')]
        .filter((d): d is PackDocumentRow => d !== undefined);
    }

    if (type === 'client_agency_export') {
      return [docMap.get('product_vision'), docMap.get('market_context'), docMap.get('target_audience_icp'), docMap.get('mvp_scope'), docMap.get('roadmap')]
        .filter((d): d is PackDocumentRow => d !== undefined);
    }

    // full_pdf_pack — all documents
    return documents;
  }

  private exportTypeLabel(type: ExportType): string {
    const labels: Partial<Record<ExportType, string>> = {
      full_pdf_pack: 'Full Product Document Pack',
      founder_summary_pdf: 'Founder Summary',
      investor_memo_pdf: 'Investor Memo',
      roadmap_pdf: 'Roadmap',
      client_agency_export: 'Client Ready Export',
    };
    return labels[type] ?? type.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
  }
}
