#!/usr/bin/env node
/**
 * Local debug APK build for the Expo app.
 *
 * Steps:
 *  1. Detect dev machine LAN IP and write apps/mobile/.env.local
 *     (EXPO_PUBLIC_API_URL, EXPO_PUBLIC_GIT_COMMIT, EXPO_PUBLIC_BUILD_TIMESTAMP,
 *      EXPO_PUBLIC_ENV — baked into the JS bundle by Metro at build time)
 *  2. Delete the previous APK so the build is unambiguous
 *  3. expo prebuild --platform android --clean
 *  4. Ensure metro.config.js has the pnpm monorepo fix
 *  5. Patch Android Gradle files where the workspace still needs it
 *  6. Verify Expo autolinking sees expo-linking
 *  7. gradlew clean assembleDebug
 *  8. Verify the APK embeds assets/index.android.bundle
 *  9. Print full artifact report: path, size, LastWriteTime, SHA256
 */
const { execFileSync, execSync } = require('child_process');
const crypto = require('crypto');
const fs = require('fs');
const os = require('os');
const path = require('path');

const root = path.resolve(__dirname, '..');
const androidDir = path.join(root, 'android');
const workspaceRoot = path.resolve(root, '../..');

// ─── LAN IP detection ────────────────────────────────────────────────────────

function detectLanIp() {
  const nets = os.networkInterfaces();
  const candidates = [];
  for (const name of Object.keys(nets)) {
    for (const net of nets[name]) {
      if (net.family === 'IPv4' && !net.internal) {
        // Prefer 192.168.x.x and 10.x.x.x (home/office LANs)
        if (net.address.startsWith('192.168.') || net.address.startsWith('10.')) {
          candidates.unshift(net.address); // prefer these
        } else {
          candidates.push(net.address);
        }
      }
    }
  }
  return candidates[0] ?? null;
}

// ─── .env.local ──────────────────────────────────────────────────────────────

function writeEnvLocal() {
  // Allow explicit override via environment variable — used for production APK builds
  // targeting https://api.signalkit.app instead of a local LAN address.
  // Example: EXPO_PUBLIC_API_URL=https://api.signalkit.app pnpm apk:debug
  const explicitApiUrl = process.env.EXPO_PUBLIC_API_URL ?? null;

  let apiUrl;
  let usingOverride = false;
  if (explicitApiUrl) {
    apiUrl = explicitApiUrl;
    usingOverride = true;
  } else {
    const lanIp = detectLanIp();
    apiUrl = lanIp ? `http://${lanIp}:4000` : 'http://10.0.2.2:4000';
  }

  const isProduction = apiUrl.startsWith('https://');
  const envName = isProduction ? 'production' : 'development';

  let gitCommit = 'unknown';
  try {
    gitCommit = execSync('git rev-parse --short HEAD', {
      cwd: workspaceRoot,
      encoding: 'utf8',
    }).trim();
  } catch {
    // git not available or not in a repo — keep 'unknown'
  }

  const buildTimestamp = new Date().toISOString();

  const lines = [
    `# Auto-generated by apk-debug.js — do not edit manually`,
    `EXPO_PUBLIC_API_URL=${apiUrl}`,
    `EXPO_PUBLIC_ENV=${envName}`,
    `EXPO_PUBLIC_GIT_COMMIT=${gitCommit}`,
    `EXPO_PUBLIC_BUILD_TIMESTAMP=${buildTimestamp}`,
  ];
  fs.writeFileSync(path.join(root, '.env.local'), lines.join('\n') + '\n', 'utf8');

  console.log(`\n✓ .env.local written:`);
  console.log(`  API URL   : ${apiUrl}${usingOverride ? '  (EXPO_PUBLIC_API_URL override)' : ''}`);
  console.log(`  ENV       : ${envName}`);
  if (!usingOverride) {
    const lanIp = detectLanIp();
    if (!lanIp) {
      console.log(`  ⚠ No LAN IP detected — using Android emulator default 10.0.2.2`);
      console.log(`    For a physical device, set EXPO_PUBLIC_API_URL=http://<your-ip>:4000`);
      console.log(`    in apps/mobile/.env.local before building.`);
    } else {
      console.log(`  LAN IP    : ${lanIp} (physical device should reach this)`);
    }
  }
  console.log(`  Git commit: ${gitCommit}`);
  console.log(`  Timestamp : ${buildTimestamp}`);

  return { apiUrl, gitCommit, buildTimestamp };
}

// ─── Delete old APK ──────────────────────────────────────────────────────────

function deleteOldApk() {
  const apkPath = path.join(androidDir, 'app', 'build', 'outputs', 'apk', 'debug', 'app-debug.apk');
  if (fs.existsSync(apkPath)) {
    fs.unlinkSync(apkPath);
    console.log(`\n✓ Deleted old APK: ${apkPath}`);
  } else {
    console.log('\n✓ No previous APK to delete');
  }
}

// ─── Metro config ────────────────────────────────────────────────────────────

const METRO_CONFIG_CONTENT = `const { getDefaultConfig } = require('expo/metro-config');
const path = require('path');

const projectRoot = __dirname;
const workspaceRoot = path.resolve(projectRoot, '../..');

const config = getDefaultConfig(projectRoot);

config.projectRoot = projectRoot;

// @expo/metro-config discovers the pnpm workspace root and uses it as the
// Metro server root, which makes "./index.js" resolve from the monorepo root.
// Force the server root back to apps/mobile so embedded debug bundles resolve
// the Expo Router entry correctly.
config.server = {
  ...config.server,
  unstable_serverRoot: projectRoot,
};

config.watchFolders = [workspaceRoot];
config.resolver.nodeModulesPaths = [
  path.resolve(projectRoot, 'node_modules'),
  path.resolve(workspaceRoot, 'node_modules'),
];

module.exports = config;
`;

function ensureMetroConfig() {
  const metroConfigPath = path.join(root, 'metro.config.js');
  const current = fs.existsSync(metroConfigPath)
    ? fs.readFileSync(metroConfigPath, 'utf8')
    : null;

  if (current !== METRO_CONFIG_CONTENT) {
    fs.writeFileSync(metroConfigPath, METRO_CONFIG_CONTENT, 'utf8');
    console.log('✓ Synced metro.config.js for pnpm monorepo bundling');
  } else {
    console.log('✓ metro.config.js already matches the required pnpm setup');
  }
}

// ─── Gradle patches ──────────────────────────────────────────────────────────

function patchAndroidGradleFiles() {
  // 1. Kotlin version pin — unversioned classpath fails Gradle resolution
  const rootBuildGradlePath = path.join(androidDir, 'build.gradle');
  const rootBuildGradle = fs.readFileSync(rootBuildGradlePath, 'utf8');
  const kotlinUnversioned = "classpath('org.jetbrains.kotlin:kotlin-gradle-plugin')";
  const kotlinVersioned = 'classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:${kotlinVersion}")';
  if (rootBuildGradle.includes(kotlinUnversioned)) {
    fs.writeFileSync(
      rootBuildGradlePath,
      rootBuildGradle.replace(kotlinUnversioned, kotlinVersioned),
      'utf8',
    );
    console.log('✓ Pinned Kotlin Gradle plugin to ${kotlinVersion} (1.9.25)');
  } else {
    console.log('✓ Kotlin Gradle plugin already pinned');
  }

  // 2. Gradle properties — daemon, JVM heap, metaspace
  const gradlePropertiesPath = path.join(androidDir, 'gradle.properties');
  let gradleProperties = fs.readFileSync(gradlePropertiesPath, 'utf8');
  let gradlePropsChanged = false;

  if (!gradleProperties.includes('org.gradle.daemon=false')) {
    gradleProperties = `${gradleProperties.trimEnd()}\norg.gradle.daemon=false\n`;
    gradlePropsChanged = true;
    console.log('✓ Disabled Gradle daemon for local builds');
  }

  // On machines with ≤8 GB RAM, G1GC compressed-oops mode places the Java heap
  // in the first 4 GB of virtual address space, blocking native heap growth and
  // causing an OOM crash during heavy Kotlin/Java compilation. Fix by:
  //   • Reducing Xmx (1536m is enough for Expo SDK 52 + New Arch compilation)
  //   • Setting HeapBaseMinAddress above 4 GB so native heap can grow freely
  //   • Reducing MaxMetaspaceSize to 256m (512m is excessive for this project)
  if (gradleProperties.includes('org.gradle.jvmargs=')) {
    const fixedJvmArgs = 'org.gradle.jvmargs=-Xmx1536m -XX:MaxMetaspaceSize=256m -XX:HeapBaseMinAddress=0x100000000';
    const current = gradleProperties.match(/org\.gradle\.jvmargs=.*/)?.[0] ?? '';
    if (current !== fixedJvmArgs) {
      gradleProperties = gradleProperties.replace(/org\.gradle\.jvmargs=.*/, fixedJvmArgs);
      gradlePropsChanged = true;
      console.log('✓ Fixed JVM args: Xmx1536m + HeapBaseMinAddress above 4 GB (prevents G1GC OOM on 7-8 GB machines)');
    }
  }

  if (gradlePropsChanged) {
    fs.writeFileSync(gradlePropertiesPath, gradleProperties, 'utf8');
  }

  // 3. app/build.gradle patches
  const appBuildGradlePath = path.join(androidDir, 'app', 'build.gradle');
  let appBuildGradle = fs.readFileSync(appBuildGradlePath, 'utf8');
  let changed = false;

  // debuggableVariants = [] — forces JS bundle embedding even in debug variant.
  // Without this the debug APK launches but shows a blank screen (no bundle).
  if (!appBuildGradle.includes('debuggableVariants = []')) {
    appBuildGradle = appBuildGradle.replace(
      '    bundleCommand = "export:embed"',
      '    bundleCommand = "export:embed"\n    debuggableVariants = []',
    );
    changed = true;
    console.log('✓ Added debuggableVariants = [] to force JS bundle in debug APK');
  }

  // PackageList namespace patch — expo-modules-autolinking 2.0.8 writes
  // expo.core.ExpoModulesPackage but the class lives in expo.modules. Patch
  // the generated Java file before javac runs. This is a build-time workaround
  // for a known autolinking bug in Expo SDK 52 + this pnpm workspace layout.
  const packageListPatch = `

// Expo SDK 52 autolinking still emits expo.core.ExpoModulesPackage in this workspace.
// Patch the generated PackageList right before compilation so Expo modules stay registered.
tasks.withType(JavaCompile).configureEach {
    it.doFirst {
        def packageList = new File("\${buildDir}/generated/autolinking/src/main/java/com/facebook/react/PackageList.java")
        if (packageList.exists() && packageList.text.contains('expo.core.ExpoModulesPackage')) {
            packageList.text = packageList.text.replace('expo.core.ExpoModulesPackage', 'expo.modules.ExpoModulesPackage')
            println '[SignalKit] Patched PackageList.java: expo.core -> expo.modules'
        }
    }
}
`;

  if (!appBuildGradle.includes('tasks.withType(JavaCompile).configureEach')) {
    appBuildGradle += packageListPatch;
    changed = true;
    console.log('✓ Added PackageList.java namespace patch (expo.core → expo.modules)');
  }

  if (changed) {
    fs.writeFileSync(appBuildGradlePath, appBuildGradle, 'utf8');
  } else {
    console.log('✓ android/app/build.gradle already patched');
  }
}

// ─── Expo autolinking verification ───────────────────────────────────────────

function verifyExpoAutolinking() {
  const autolinkingBin = require.resolve(
    'expo-modules-autolinking/bin/expo-modules-autolinking.js',
    { paths: [require.resolve('expo/package.json', { paths: [root] })] },
  );

  const searchOutput = execFileSync(
    process.execPath,
    [autolinkingBin, 'search', '--platform', 'android', '--project-root', root],
    { encoding: 'utf8' },
  );

  if (!searchOutput.includes('expo-linking') || !searchOutput.includes('ExpoLinkingModule')) {
    console.error('\n✗ Expo autolinking does not include expo-linking / ExpoLinkingModule.');
    process.exit(1);
  }
  console.log('✓ Expo autolinking includes expo-linking / ExpoLinkingModule');

  const packageListTarget = path.join(
    androidDir, 'build', 'generated', 'autolinking', 'ExpoModulesPackageList.java',
  );
  fs.mkdirSync(path.dirname(packageListTarget), { recursive: true });

  execFileSync(
    process.execPath,
    [
      autolinkingBin,
      'generate-package-list',
      '--platform', 'android',
      '--project-root', root,
      '--target', packageListTarget,
      '--namespace', 'expo.modules',
    ],
    { stdio: 'inherit' },
  );

  const packageList = fs.readFileSync(packageListTarget, 'utf8');
  if (!packageList.includes('expo.modules.linking.ExpoLinkingModule.class')) {
    console.error('\n✗ Generated ExpoModulesPackageList.java is missing ExpoLinkingModule.');
    process.exit(1);
  }
  console.log('✓ Generated ExpoModulesPackageList.java includes ExpoLinkingModule');
}

// ─── APK verification ────────────────────────────────────────────────────────

function verifyApk(apkPath, buildMeta) {
  if (!fs.existsSync(apkPath)) {
    console.error(`\n✗ APK not found at ${apkPath}`);
    process.exit(1);
  }

  const apkContents = execSync(`tar -tf "${apkPath}"`, { encoding: 'utf8' });
  if (!apkContents.includes('assets/index.android.bundle')) {
    console.error('\n✗ APK is missing assets/index.android.bundle — JS bundle was not embedded.');
    process.exit(1);
  }

  const stat = fs.statSync(apkPath);
  const sha256 = crypto.createHash('sha256').update(fs.readFileSync(apkPath)).digest('hex');

  console.log('\n╔═══════════════════════════════════════════════════╗');
  console.log('║           NEW APK ARTIFACT REPORT                ║');
  console.log('╚═══════════════════════════════════════════════════╝');
  console.log(`  Path        : ${apkPath}`);
  console.log(`  Size        : ${(stat.size / 1024 / 1024).toFixed(2)} MB`);
  console.log(`  LastWrite   : ${stat.mtime.toISOString()}`);
  console.log(`  SHA256      : ${sha256}`);
  console.log(`  Bundle      : assets/index.android.bundle ✓`);
  console.log(`  API URL     : ${buildMeta.apiUrl}`);
  console.log(`  Git commit  : ${buildMeta.gitCommit}`);
  console.log(`  Built at    : ${buildMeta.buildTimestamp}`);
  console.log('');
  console.log('  Install command:');
  console.log(`  adb uninstall com.signalkit.app`);
  console.log(`  adb install "${apkPath}"`);
  console.log('');

  return { apkPath, size: stat.size, mtime: stat.mtime, sha256 };
}

// ─── Shell helper ────────────────────────────────────────────────────────────

function run(command, options = {}) {
  console.log(`\n> ${command}`);
  execSync(command, { stdio: 'inherit', ...options });
}

// ─── Main ────────────────────────────────────────────────────────────────────

console.log('\n╔═══════════════════════════════════════════════════╗');
console.log('║          SignalKit local APK build                ║');
console.log('╚═══════════════════════════════════════════════════╝\n');

// Step 1: write .env.local with LAN IP + build metadata
const buildMeta = writeEnvLocal();

// Step 2: delete previous APK so we know the new one is fresh
deleteOldApk();

// Step 3: prebuild regenerates android/ (includes plugin registration for
//         expo-secure-store, expo-haptics now that they're in app.config.ts)
run('expo prebuild --platform android --clean', { cwd: root });

// Step 4: ensure metro.config.js is correct after prebuild
ensureMetroConfig();

// Step 5: apply Gradle patches (debuggableVariants, Kotlin pin, PackageList fix)
patchAndroidGradleFiles();

// Step 6: verify autolinking
verifyExpoAutolinking();

// Step 7: build
const gradlew = process.platform === 'win32'
  ? path.join(androidDir, 'gradlew.bat')
  : path.join(androidDir, 'gradlew');

run(`"${gradlew}" clean assembleDebug`, { cwd: androidDir });

// Step 8: verify + report
const apkPath = path.join(androidDir, 'app', 'build', 'outputs', 'apk', 'debug', 'app-debug.apk');
verifyApk(apkPath, buildMeta);
